/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Git references within a repository
 */
export interface GitReference {
  ref: string;
  node_id: string;
  url: string;
  object: {
    type: string;
    /**
     * SHA for the reference
     */
    sha: string;
    url: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
