version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/actions"
    assignees:
      - "q453358"
      - "qxv2156"
    reviewers:
      - "q453358"
      - "qxv2156"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "maven"
    directory: "/.github/actions/make-quarkus-stub"
    schedule:
      interval: "daily"
    assignees:
      - "qxv2156"
      - "q453358"
    reviewers:
      - "UNITY/unity-devops"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 2

