name: make-quarkus-stub
description: install tools and setup stub
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: setup java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}
    - name: setup maven
      uses: unity/setup-maven@v1
    - name: create
      working-directory: ${{ env.WORKING_DIRECTORY }}
      shell: bash
      run: ${{ github.action_path }}/create-quarkus-app.bash
