name: 'review-new-app-issue'
description: 'Review an issue of type "New App".'
inputs:
  GITHUB_TOKEN:
    description: the GITHUB_TOKEN to authenticate to the API
    required: true
  working-directory:
    description: working directory to run the action in
    required: false

runs:
  using: 'node16'
  main: '../../../actions/dist/actions/review-new-app-issue.js'
