name: 'create-app'
description: 'Create new UNITY app'
inputs:
  GITHUB_TOKEN:
    description: the GITHUB_TOKEN to authenticate to the API
    required: true
  working-directory:
    description: working directory to run the action in
    required: false

runs:
  using: 'node16'
  main: 'actions/dist/actions/create-app.js'
