/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Repository Collaborator Permission
 */
export interface RepositoryCollaboratorPermission {
  permission: string;
  role_name: string;
  user: null | Collaborator;
  [k: string]: unknown;
}
/**
 * Collaborator
 */
export interface Collaborator {
  login: string;
  id: number;
  email?: string | null;
  name?: string | null;
  node_id: string;
  avatar_url: string;
  gravatar_id: string | null;
  url: string;
  html_url: string;
  followers_url: string;
  following_url: string;
  gists_url: string;
  starred_url: string;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: string;
  received_events_url: string;
  type: string;
  site_admin: boolean;
  permissions?: {
    pull: boolean;
    triage?: boolean;
    push: boolean;
    maintain?: boolean;
    admin: boolean;
    [k: string]: unknown;
  };
  role_name: string;
  [k: string]: unknown;
}
