/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The public key used for setting Actions Secrets.
 */
export interface ActionsPublicKey {
  /**
   * The identifier for the key.
   */
  key_id: string;
  /**
   * The Base64 encoded public key.
   */
  key: string;
  id?: number;
  url?: string;
  title?: string;
  created_at?: string;
  [k: string]: unknown;
}
