name: 'build-actions'
description: 'Build js actions'

runs:
  using: composite
  steps:
    - name: debug info
      if: ${{ runner.debug }}
      shell: bash
      env:
        GITHUB_JSON: ${{ toJSON(github) }}
      run: |
        echo "$GITHUB_JSON" | jq .
        git config --list
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: ./actions/package-lock.json
    - uses: actions/cache@v3
      id: cache
      with:
        key: actions-${{ hashFiles('./actions/**') }}
        path: ./actions
    - name: npm ci
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      working-directory: ./actions
      shell: bash
      run: npm ci --force
    - name: tsc
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      working-directory: ./actions
      shell: bash
      run: npx tsc
