env:
  browser: false
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files:
      - src/**/*.ts
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
root: true
rules:
  '@typescript-eslint/no-explicit-any':
    - error
  '@typescript-eslint/no-unused-vars':
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true
  require-await:
    - error
  semi:
    - error
    - always
