name: Create Prod K8s Objects
on:
  workflow_dispatch:

jobs:
  create-k8s-objects:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 30
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: create-prod-k8s-objects
        uses: ./.github/actions/create-prod-k8s-objects
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          PROD_KUBERNETES_TOKEN: ${{ secrets.PROD_CLUSTER_KUBERNETES_TOKEN }}
          PROD_KUBERNETES_HOST: ${{ secrets.PROD_CLUSTER_KUBERNETES_HOST }}
          PROD_KUBERNETES_NAMESPACE: ${{ secrets.PROD_CLUSTER_KUBERNETES_NAMESPACE }}
          working-directory: actions
