name: create new UNITY app
on:
  issues:
    types:
      - labeled

jobs:
  create-app:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 20
    permissions: write-all
    concurrency:
      group: ${{ github.job }}-${{ github.event.issue.id }}
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: create-app
        uses: ./.github/actions/create-app/
        with:
          GITHUB_TOKEN: ${{secrets.UNITY_BOT_TOKEN}}
          working-directory: actions
