name: Issue Updated
on:
  issues:
    types:
      - edited
      - reopened
      - labeled
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.event.issue.number }}
  cancel-in-progress: false
jobs:
  issue-updated:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 30
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: issue-updated
        uses: ./.github/actions/issue-updated
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          INT_KUBERNETES_TOKEN: ${{ secrets.INT_KUBERNETES_TOKEN }}
          INT_KUBERNETES_HOST: ${{ secrets.INT_KUBERNETES_HOST }}
          INT_KUBERNETES_NAMESPACE: ${{ secrets.INT_KUBERNETES_NAMESPACE }}
          PROD_KUBERNETES_TOKEN: ${{ secrets.PROD_KUBERNETES_TOKEN }}
          PROD_KUBERNETES_HOST: ${{ secrets.PROD_KUBERNETES_HOST }}
          PROD_KUBERNETES_NAMESPACE: ${{ secrets.PROD_KUBERNETES_NAMESPACE }}
          working-directory: actions
