name: Issue Updated
on:
  issues:
    types:
      - edited
      - reopened
      - labeled
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.event.issue.number }}
  cancel-in-progress: false
jobs:
  new-app-issue:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: issue-updated
        uses: ./.github/actions/issue-updated
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          working-directory: actions
