name: lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  editorconfig-checker:
    permissions:
      contents: read
      id-token: write
    runs-on: atc-ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: unity/setup-editorconfig-checker@v1
      - run: editorconfig-checker
  check-todos:
    permissions:
      contents: read
      id-token: write
    runs-on: atc-ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: unity/check-todos@v1
        with:
          pathspec: "'*'"
