name: Make App Stub
on:
  workflow_dispatch:
    inputs:
      repository:
        description: name of the app repo inside the UNITY org
        required: true
      type:
        required: true
        description: type of stub to create
        type: choice
        options:
          - angular
          - quarkus
      name:
        required: true
        description: name of the deployable to create
      dry-run:
        required: false
        description: dry-run flag (if true, don't push results to the repo)
      javaVersion:
        required: true
        description: the Java version used for generating the Quarkus stub
      javaDistribution:
        required: true
        description: the Java distribution used for generating the Quarkus stub
      nodeVersion:
        required: true
        description: the node version used for the application generation

concurrency:
  group: make-stub-${{ github.event.inputs.repository }}
  cancel-in-progress: false
jobs:
  make-stub:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: debug info
        if: ${{ runner.debug }}
        shell: bash
        env:
          GITHUB_JSON: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_JSON" | jq .
          git config --list
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.UNITY_BOT_TOKEN }}
          path: unity
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ github.event.inputs.repository }}
          token: ${{ secrets.UNITY_BOT_TOKEN }}
          path: ${{ github.event.inputs.repository }}
      - name: make-angular-stub
        if: ${{ github.event.inputs.type == 'angular' }}
        env:
          ORG: ${{ github.repository_owner }}
          NAME: ${{ github.event.inputs.name }}
          WORKING_DIRECTORY: ${{ github.event.inputs.repository }}
          NODE_VERSION: ${{ github.event.inputs.nodeVersion }}
          # see https://github.com/angular/angular-cli/releases
          ANGULAR_VERSION: '16'
        uses: ./unity/.github/actions/make-angular-stub
      - name: make-quarkus-stub
        if: ${{ github.event.inputs.type == 'quarkus' }}
        env:
          ORG: ${{ github.repository_owner }}
          NAME: ${{ github.event.inputs.name }}
          WORKING_DIRECTORY: ${{ github.event.inputs.repository }}
          NODE_VERSION: ${{ github.event.inputs.nodeVersion }}
          JAVA_VERSION: ${{ github.event.inputs.javaVersion }}
          JAVA_DISTRIBUTION: ${{ github.event.inputs.javaDistribution }}
        uses: ./unity/.github/actions/make-quarkus-stub
      - name: commit
        shell: bash
        working-directory: ${{ github.event.inputs.repository }}
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@no-mail.com'
          git add ${{ github.event.inputs.name}}
          git commit --all --message 'create ${{ github.event.inputs.type }} stub: ${{ github.event.inputs.name }}'
          git pull --rebase origin main
      - name: push
        if: ${{ github.event.inputs.dry-run != 'true' }}
        shell: bash
        working-directory: ${{ github.event.inputs.repository }}
        run: |
          git push -u origin main


