name: |
  "New UNITY App" issue
on:
  issues:
    types:
      - edited
      - reopened
      - labeled
  issue_comment:
    types:
      - created

concurrency:
  group: new-app-issue-${{ github.event.issue.number }}
  cancel-in-progress: false
jobs:
  new-app-issue:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    outputs:
      app-repository: ${{ steps.new-app-issue.outputs.app-repository }}
      make-angular-stub: ${{ steps.new-app-issue.outputs.make-angular-stub }}
      make-quarkus-stub: ${{ steps.new-app-issue.outputs.make-quarkus-stub }}
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: new-app-issue
        id: new-app-issue
        uses: ./.github/actions/new-app-issue
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          working-directory: actions
  make-angular-stub:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 20
    needs: new-app-issue
    if: needs.new-app-issue.outputs.make-angular-stub
    concurrency:
      group: make-stub
    env:
      NAME: ${{ needs.new-app-issue.outputs.make-angular-stub }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ needs.new-app-issue.outputs.app-repository }}
          token: ${{ secrets.UNITY_BOT_TOKEN }}
      - uses: pmd/setup-git@v1
        with:
          setup-branch: false
        env:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: make stub
        shell: bash
        run: ${{ github.action_path }}/make-stubs/angular.bash ${{ env.NAME }}
      - name: commit and push
        shell: bash
        run: |
          git add ${{ inputs.name }}
          git add .github/workflows/*.yaml
          git commit --all --message 'create quarkus stub: ${{ env.NAME }}'
          git push -u origin main
  make-quarkus-stub:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 20
    needs: new-app-issue
    if: needs.new-app-issue.outputs.make-quarkus-stub
    concurrency:
      group: make-stub
    env:
      NAME: ${{ needs.new-app-issue.outputs.make-quarkus-stub }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ needs.new-app-issue.outputs.app-repository }}
          token: ${{ secrets.UNITY_BOT_TOKEN }}
      - uses: pmd/setup-git@v1
        with:
          setup-branch: false
        env:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: setup maven
        uses: pmd/setup-maven@v1
      - name: make stub
        shell: bash
        run: ${{ github.action_path }}/make-stubs/quarkus.bash ${{ env.NAME }}
      - name: commit and push
        shell: bash
        run: |
          git add ${{ inputs.name }}
          git add .github/workflows/*.yaml
          git commit --all --message 'create quarkus stub: ${{ env.NAME }}'
          git push -u origin main
