name: |
  "New UNITY App" issue
on:
  issues:
    types:
      - edited
      - reopened
      - labeled
  issue_comment:
    types:
      - created

jobs:
  new-app-issue:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 20
    permissions: write-all
    concurrency:
      group: new-app-issue-${{ github.event.issue.id }}
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: new-app-issue
        uses: ./.github/actions/new-app-issue
        with:
          GITHUB_TOKEN: ${{secrets.UNITY_BOT_TOKEN}}
          working-directory: actions
