name: Recreate App Service Account
on:
  workflow_dispatch:
    inputs:
      repositoryRegex:
        description: regex to match the name of the app repo inside the UNITY org
        required: true
        default: app-test
        type: string
      environment:
        description: environment to update the secrets for
        required: true
        type: choice
        options:
          - int
          - prod
jobs:
  recreate-app-sa:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 30
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: upsert-int-k8s-objects
        if: ${{ inputs.environment == 'int' }}
        uses: ./.github/actions/upsert-k8s-object
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          INT_KUBERNETES_TOKEN: ${{ secrets.INT_KUBERNETES_TOKEN }}
          INT_KUBERNETES_HOST: ${{ secrets.INT_KUBERNETES_HOST }}
          INT_KUBERNETES_NAMESPACE: ${{ secrets.INT_KUBERNETES_NAMESPACE }}
          environment: ${{ inputs.environment }}
          repoRegex: ${{ inputs.repositoryRegex }}
      - name: upsert-prod-k8s-objects
        if: ${{ inputs.environment == 'prod' }}
        uses: ./.github/actions/upsert-k8s-object
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          PROD_KUBERNETES_TOKEN: ${{ secrets.PROD_KUBERNETES_TOKEN }}
          PROD_KUBERNETES_HOST: ${{ secrets.PROD_KUBERNETES_HOST }}
          PROD_KUBERNETES_NAMESPACE: ${{ secrets.PROD_KUBERNETES_NAMESPACE }}
          environment: ${{ inputs.environment }}
          repoRegex: ${{ inputs.repositoryRegex }}
