name: review "New UNITY App" issue
on:
  issues:
    types:
      - edited
      - reopened
      - labeled
      - unlabeled
  issue_comment:
    types:
      - created

jobs:
  review-new-app-issue:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: review-new-app-issue
        uses: ./.github/actions/review-new-app-issue/
        with:
          GITHUB_TOKEN: ${{secrets.UNITY_BOT_TOKEN}}
