name: handle all changes to a "New App" issue
on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  review-new-app-issue:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: review-new-app-issue
        uses: ./.github/actions/review-new-app-issue/
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
