name: store-config
on:
  workflow_dispatch:
jobs:
  store-secrets:
    runs-on: atc-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: write config
        shell: bash
        env:
          # ⚠️ never add any secret information here (such as tokens). ANYONE can download the artifact. ⚠️
          TEST_KUBERNETES_HOST: ${{ secrets.TEST_KUBERNETES_HOST }}
          TEST_KUBERNETES_NAMESPACE: ${{ secrets.TEST_KUBERNETES_NAMESPACE }}
          INT_KUBERNETES_HOST: ${{ secrets.INT_KUBERNETES_HOST }}
          INT_KUBERNETES_NAMESPACE: ${{ secrets.INT_KUBERNETES_NAMESPACE }}
          PROD_KUBERNETES_HOST: ${{ secrets.PROD_KUBERNETES_HOST }}
          PROD_KUBERNETES_NAMESPACE: ${{ secrets.PROD_KUBERNETES_NAMESPACE }}
        run: |
          echo "${{ format('TEST_KUBERNETES_HOST{0} $TEST_KUBERNETES_HOST', ':') }}" >> config.yaml
          echo "${{ format('TEST_KUBERNETES_NAMESPACE{0} $TEST_KUBERNETES_NAMESPACE', ':') }}" >> config.yaml
          echo "${{ format('INT_KUBERNETES_HOST{0} $INT_KUBERNETES_HOST', ':') }}" >> config.yaml
          echo "${{ format('INT_KUBERNETES_NAMESPACE{0} $INT_KUBERNETES_NAMESPACE', ':') }}" >> config.yaml
          echo "${{ format('PROD_KUBERNETES_HOST{0} $PROD_KUBERNETES_HOST', ':') }}" >> config.yaml
          echo "${{ format('PROD_KUBERNETES_NAMESPACE{0} $PROD_KUBERNETES_NAMESPACE', ':') }}" >> config.yaml
      - name: upload config
        uses: actions/upload-artifact@v3
        with:
          name: config.yaml
          path: config.yaml
