name: Sync Master Keys From V1 to V2
on:
  workflow_dispatch:
    inputs:
      repositoryRegex:
        description: Regex to match the name of the app repo inside the UNITY org
        required: true
        default: app-test
        type: string
      overwrite:
        description: Override existing K8s secret
        required: true
        default: false
        type: boolean
      environment:
        description: Environment to update the secrets for
        required: true
        type: choice
        options:
          - test
          - int
          - prod
jobs:
  sync-master-keys-from-v1-to-v2:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 30
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: sync-master-keys-from-v1-to-v2-test
        if: ${{ inputs.environment == 'test' }}
        uses: ./.github/actions/sync-master-keys-from-v1-to-v2
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          KUBERNETES_TOKEN: ${{ secrets.TEST_KUBERNETES_TOKEN }}
          KUBERNETES_HOST: ${{ secrets.TEST_KUBERNETES_HOST }}
          KUBERNETES_NAMESPACE: ${{ secrets.TEST_KUBERNETES_NAMESPACE }}
          environment: ${{ inputs.environment }}
          repository-regex: ${{ inputs.repositoryRegex }}
          overwrite: ${{ inputs.overwrite }}
      - name: sync-master-keys-from-v1-to-v2-int
        if: ${{ inputs.environment == 'int' }}
        uses: ./.github/actions/sync-master-keys-from-v1-to-v2
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          KUBERNETES_TOKEN: ${{ secrets.INT_KUBERNETES_TOKEN }}
          KUBERNETES_HOST: ${{ secrets.INT_KUBERNETES_HOST }}
          KUBERNETES_NAMESPACE: ${{ secrets.INT_KUBERNETES_NAMESPACE }}
          environment: ${{ inputs.environment }}
          repository-regex: ${{ inputs.repositoryRegex }}
          overwrite: ${{ inputs.overwrite }}
      - name: sync-master-keys-from-v1-to-v2-prod
        if: ${{ inputs.environment == 'prod' }}
        uses: ./.github/actions/sync-master-keys-from-v1-to-v2
        with:
          GITHUB_TOKEN: ${{ secrets.UNITY_BOT_TOKEN }}
          KUBERNETES_TOKEN: ${{ secrets.PROD_KUBERNETES_TOKEN }}
          KUBERNETES_HOST: ${{ secrets.PROD_KUBERNETES_HOST }}
          KUBERNETES_NAMESPACE: ${{ secrets.PROD_KUBERNETES_NAMESPACE }}
          environment: ${{ inputs.environment }}
          repository-regex: ${{ inputs.repositoryRegex }}
          overwrite: ${{ inputs.overwrite }}
