name: test-actions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
  eslint:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-actions
      - name: eslint
        working-directory: ./actions
        run: npx eslint src
  test:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: test
        working-directory: ./actions
        run: npm test -- --verbose
  test-create-angular-stub:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    env:
      ORG: ${{ github.repository_owner }}
      NODE_VERSION: '16'
      WORK_DIR: test-stubs
      IMAGE: "containers.atc-github.azure.cloud.bmw/unity/test-stubs:foo"
      MOVING_IMAGE: "containers.atc-github.azure.cloud.bmw/unity/test-stubs:latest"
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: create working directory
        run: mkdir "$WORK_DIR"
      - name: init repo
        working-directory: ${{ env.WORK_DIR }}
        run: git init
      - name: make-angular-stub
        uses: ./.github/actions/make-angular-stub
        env:
          NAME: ui
          WORKING_DIRECTORY: ${{ env.WORK_DIR }}
          ANGULAR_VERSION: '16'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install chromium
        run: |
          sudo apt-get update
          sudo apt install chromium-browser
      - name: ng test
        working-directory: ${{ env.WORK_DIR }}/ui
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: npx ng test --browsers=ChromeHeadless --watch=false
      - name: lint
        working-directory: ${{ env.WORK_DIR }}/ui
        run: npx ng lint
      - name: ci
        working-directory: ${{ env.WORK_DIR }}/ui
        run: npm ci --force
      - name: build
        working-directory: ${{ env.WORK_DIR }}/ui
        run: npx ng build -c production
      - name: docker build
        working-directory: ${{ env.WORK_DIR }}/ui
        run: |
          docker build -t "${{ env.IMAGE }}" -t "${{ env.MOVING_IMAGE }}" . --label "org.opencontainers.image.source=${{ github.event.repository.html_url }}"

  test-create-quarkus-stub:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    env:
      ORG: ${{ github.repository_owner }}
      NODE_VERSION: '16'
      WORK_DIR: test-stubs
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: create working directory
        run: mkdir "$WORK_DIR"
      - name: init repo
        working-directory: ${{ env.WORK_DIR }}
        run: git init
      - name: make-quarkus-stub
        uses: ./.github/actions/make-quarkus-stub
        env:
          NAME: api
          WORKING_DIRECTORY: ${{ env.WORK_DIR }}
          JAVA_VERSION: '17'
          JAVA_DISTRIBUTION: 'zulu'
      - name: mvn package
        working-directory: ${{ env.WORK_DIR }}/api
        run: mvn --batch-mode clean package
