name: test-actions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
  eslint:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-actions
      - name: eslint
        working-directory: ./actions
        run: npx eslint src
  test:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: test
        working-directory: ./actions
        run: npm test -- --verbose
  test-create-stubs:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    env:
      ORG: ${{ github.repository_owner }}
      NODE_VERSION: '16'
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: create working directory
        run: mkdir test-stubs
      - name: make-angular-stub
        uses: ./.github/actions/make-angular-stub
        env:
          NAME: ui
          WORKING_DIRECTORY: test-stubs
          ANGULAR_VERSION: '15'
      - name: install chromium
        run: |
          sudo apt-get update
          sudo apt install chromium-browser
      - name: ng test
        working-directory: test-stubs/ui
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: npx ng test --browsers=ChromeHeadless --watch=false
      - name: make-quarkus-stub
        uses: ./.github/actions/make-quarkus-stub
        env:
          NAME: api
          WORKING_DIRECTORY: test-stubs
          JAVA_VERSION: '17'
          JAVA_DISTRIBUTION: 'zulu'
      - name: mvn test
        working-directory: test-stubs/api
        run: mvn test