name: test-actions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
  eslint:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-actions
      - name: eslint
        working-directory: ./.github/actions
        run: npx eslint
  test:
    runs-on: atc-ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: build-actions
        uses: ./.github/actions/build-actions
      - name: test
        working-directory: ./.github/actions
        run: npm test
